mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
authentication: [""]
allow-lan: true
mode: Rule
log-level: info
ipv6: true
external-controller: :9999
external-ui: ui
secret: 
tun: {enable: false}
experimental: {ignore-resolve-fail: true, interface-name: en0}

find-process-mode: "off"
routing-mark: 7894
dns:
  enable: true
  listen: :1053
  use-hosts: true
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time-ios.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.qq.com'
    - '+.tencent.com'
    - '+.steamcontent.com'
    - '+.srv.nintendo.net'
    - '*.n.n.srv.nintendo.net'
    - '+.cdn.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - 'na.b.g-tun.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.ff14.sdo.com'
    - 'ff.dorado.sdo.com'
    - '*.mcdn.bilivideo.cn'
    - '+.media.dssott.com'
    - 'shark007.net'
    - '+.market.xiaomi.com'
    - '+.cmbchina.com'
    - '+.cmbimg.com'
    - 'adguardteam.github.io'
    - 'adrules.top'
    - 'anti-ad.net'
    - 'local.adguard.org'
    - 'static.adtidy.org'
    - '+.sandai.net'
    - '+.n0808.com'
    - '+.3gppnetwork.org'
    - '+.uu.163.com'
    - 'ps.res.netease.com'
    - '+.oray.com'
    - '+.orayimg.com'
  nameserver: [https://223.5.5.5/dns-query, https://doh.pub/dns-query, tls://dns.rubyfish.cn:853]
  fallback: [https://1.0.0.1/dns-query, https://8.8.4.4/dns-query, https://doh.opendns.com/dns-query]
  fallback-filter:
    geoip: true
    domain:
      - '+.bing.com'
      - '+.linkedin.com'
hosts:
   'time.android.com': 203.107.6.88
   'time.facebook.com': 203.107.6.88  
   'localhost': 127.0.0.1
proxies:
  - name: TW
    type: vless
    server: 34.80.173.121
    port: 443
    uuid: 58a45875-6a18-4a91-9556-2d00e0e3cc94
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: itunes.apple.com
    reality-opts:
      public-key: 5os-UBV1w11xtkpPJA9QZRL4q49BNwoyjDB4yJRYoko
    client-fingerprint: chrome

  - name: HK
    type: vless
    server: 2600:1900:41a0:20b:0:d:0:0
    port: 443
    uuid: 58a45875-6a18-4a91-9556-2d00e0e3cc94
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: itunes.apple.com
    reality-opts:
      public-key: 5os-UBV1w11xtkpPJA9QZRL4q49BNwoyjDB4yJRYoko
    client-fingerprint: chrome

  - name: JP
    type: vless
    server: 138.2.40.110
    port: 443
    uuid: 3f7e2e88-a6b2-486d-85f3-e1efdcab8ecb
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: itunes.apple.com
    reality-opts:
      public-key: TSNtcEdzYv6PI3awG-fwVtl9XufVNigDEVDqpK0htjg
    client-fingerprint: chrome

  - name: KR
    type: vless
    server: 146.56.159.99
    port: 443
    uuid: 269b1822-9140-49fb-a59e-0b039a4a83f9
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: itunes.apple.com
    reality-opts:
      public-key: cRKw0wE5VPrgxdvpoIReC1Ot4vrwJTcxBTAmRpD8Ezw
      short-id: fe60318a2ee38f77
    client-fingerprint: chrome

  - name: US
    type: vless
    server: 107.173.156.139
    port: 443
    uuid: af583733-1915-4bec-b0ab-ba1f82488862
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: itunes.apple.com
    reality-opts:
      public-key: 907EIwpMSetGcfQx7cG8drq2AWPGCXY6HYwtCVwpIRQ
      short-id: 4c24b8176d0b351b
    client-fingerprint: chrome

  - name: dns-out
    type: dns

proxy-groups:
  - name: AUTO
    type: url-test
    url: https://www.apple.com
    interval: 300
    tolerance: 150
    expected-status: 204
    proxies:
      - TW
      - HK
      - JP
      - KR
      - US

  - name: MANUAL
    type: select
    proxies:
      - AUTO
      - DIRECT
      - TW
      - HK
      - JP
      - KR
      - US


rules:
 - RULE-SET,lancidr,DIRECT
 - RULE-SET,private,DIRECT
 - GEOSITE,private,DIRECT
 - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - IP-CIDR,28.0.0.1/8,REJECT,no-resolve
 - IP-CIDR6,::1/128,REJECT,no-resolve 
 - AND,((NETWORK,TCP),(DST-PORT,5228-5230)),DIRECT
 - AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),DIRECT
 - AND,((NETWORK,UDP),(DST-PORT,123)),DIRECT
 - DST-PORT,123/136/137-139,DIRECT,udp


 - RULE-SET,applications,DIRECT
 - RULE-SET,netflix,MANUAL
 - DOMAIN,clash.razord.top,DIRECT
 - DOMAIN,yacd.haishan.me,DIRECT
 - RULE-SET,blockAD,REJECT
 - RULE-SET,NoPcdn,REJECT
 - RULE-SET,NoOperatorHijack,REJECT
 - DOMAIN-KEYWORD,szbdyd,REJECT

 - DOMAIN-KEYWORD,gemini,MANUAL
 - DOMAIN-KEYWORD,builtwith,DIRECT
 - DOMAIN-KEYWORD,velo,DIRECT
 - DOMAIN-KEYWORD,xda,DIRECT
 - DOMAIN-KEYWORD,daxiaamu,DIRECT
 - DOMAIN-KEYWORD,nodeseek,DIRECT
 - DOMAIN-KEYWORD,wechat,DIRECT
 - DOMAIN-KEYWORD,macked,MANUAL
 - DOMAIN-KEYWORD,sourceforge,MANUAL
 - DOMAIN-KEYWORD,porn,AUTO
 - DOMAIN-KEYWORD,tanhuazu,MANUAL
 - DOMAIN-KEYWORD,pikpak,MANUAL
 - DOMAIN-KEYWORD,v2rayssr,MANUAL
 - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,MANUAL
 - DOMAIN-SUFFIX,googleapis.cn,MANUAL

 - RULE-SET,icloud,DIRECT
 - RULE-SET,apple,DIRECT
 - RULE-SET,ai,KR
 - RULE-SET,google,MANUAL
 - RULE-SET,YouTube,MANUAL
 - RULE-SET,proxy,MANUAL
 - RULE-SET,direct,DIRECT
 - RULE-SET,cncidr,DIRECT
 - RULE-SET,telegramcidr,MANUAL
 - RULE-SET,collection,DIRECT,no-resolve
 - GEOIP,LAN,DIRECT,no-resolve
 - GEOIP,CN,DIRECT,no-resolve
 - MATCH,MANUAL
rule-providers:
  blockAD:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  ai:
    type: http
    behavior: domain
    format: text
    path: ./rules/ai.list
    url: "https://raw.githubusercontent.com/DustinWin/ruleset_geodata/clash-ruleset/ai.list"
    interval: 86400

  NoPcdn:
    type: http
    behavior: domain
    format: text
    path: ./rules/NoPcdn.list
    url: "https://ruleset.skk.moe/List/non_ip/reject-no-drop.conf"
    interval: 86400

  NoOperatorHijack:
    type: http
    behavior: domain
    format: text
    path: ./rules/NoOperatorHijack.list
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Hijacking/Hijacking.list"
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  netflix:
    type: http
    behavior: domain
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.list"
    path: ./ruleset/google.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list"
    path: ./ruleset/YouTube.list
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  collection: 
    type: http
    behavior: classical
    format: yaml
    path: ./ruleset/collection.yaml
    url: "https://gist.githubusercontent.com/cnfree8964/0864fd1d2e88936a095fb40d74ce4993/raw/collection.yaml"

